### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by Tephilla**
Request to include Marie Kerjean's talk

### CODE REVIEW

**Comment by Tephilla** [comment]
Thanks for the merge. Unable to add picture of the speaker to img directory.

**Comment by vcvpaiva** [comment]
Why Tephilla? do you know? permissions, the picture was too big?
thanks!
Valeria

**Comment by Tephilla** [comment]
I didn't have the permission to upload them.
Marie said we could use the image from her webpage
<https://lipn.univ-paris13.fr/~kerjean/> (attached). Could you please add
it, if possible?

Best regards,
Tephi

**Comment by vcvpaiva** [comment]
Thanks for being the "guinea pig" for uploading collaborations, Tephilla!

I did add the picture and I think I should warn people to have a very short
description and not to use dates simply numeric, as conventions are
different in the US/rest of the world.

 but the video is producing the default icon and I don't know how to solve
this, will ask Prathyush.

**Comment by Tephilla** [comment]
Thank you! I'm more than happy to be of help.

I just noticed the description, date format and icon issues.
Would it be useful, to have a simple Google form that does these
validations- character limit for text, formatting for the date, maybe a
size/resolution limit for the picture as well?

It's more cumbersome than having a PR on GitHub, but more people might be
willing to submit talks using a user friendly Google form, plus it does the
validation for us. Would this work for us?

**Comment by vcvpaiva** [comment]
>It's more cumbersome than having a PR on GitHub, but more people might be
willing to submit talks using a user friendly Google form, plus it does the
validation for us. Would this work for us?

It might work, but it's not a priority right now. So I will leave the issue open, while we see if others have issues.

**Pull request merged**
